# Use an official Node.js runtime as a parent image
FROM node:18-alpine AS frontend

ARG VITE_APP_BASE_API_URL
ARG VITE_APP_ENV

# Set the working directory to /app
WORKDIR /app

# Copy package.json and other necessary files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY --chown=node:node . ./

# Set the build arguments as environment variables for the build process
ENV VITE_APP_BASE_API_URL=$VITE_APP_BASE_API_URL
ENV VITE_APP_ENV=$VITE_APP_ENV

# Debugging - Print the environment variables
RUN echo "$VITE_APP_BASE_API_URL"
RUN echo "$VITE_APP_ENV"

# Build the TypeScript code
RUN npm run build

# Production environment
FROM nginx:1.29.5-alpine3.23

# Copy built files from the frontend stage
COPY --from=frontend /app/build /usr/share/nginx/html

# Expose port 80 for the Nginx server
EXPOSE 80

# Start Nginx in the foreground when the container starts
CMD ["nginx", "-g", "daemon off;"]