services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
        VITE_APP_BASE_API_URL: ${VITE_APP_BASE_API_URL}
        VITE_APP_ENV: ${VITE_APP_ENV}
    ports:
      - "80:80"
    environment:
      - VITE_APP_BASE_API_URL=${VITE_APP_BASE_API_URL}
      - VITE_APP_ENV=${VITE_APP_ENV}
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PROVE_CLIENT_ID=${PROVE_CLIENT_ID}
      - PROVE_CLIENT_SECRET=${PROVE_CLIENT_SECRET}
      - APPLICATION_DOMAIN=${APPLICATION_DOMAIN}
